import {Article, UserData} from '@/types/profile';

export const mockArticles: Article[] = [
  {
    id: 1,
    title: 'Introduction to Web3 Development',
    description: 'A comprehensive guide to getting started with Web3 development',
    publishedAt: '2024-01-15',
    readTime: 8,
    stars: 156,
    views: 1200,
    tags: ['web3', 'blockchain', 'ethereum'],
    coverImage: null,
    tokenGated: true,
    blockchain: 'Ethereum',
    tokenReward: 10,
  },
  {
    id: 2,
    title: 'Building DApps with React',
    description: 'Learn how to build decentralized applications using React',
    publishedAt: '2024-01-10',
    readTime: 12,
    stars: 89,
    views: 800,
    tags: ['react', 'dapp', 'tutorial'],
    coverImage: null,
    tokenGated: false,
    nftRequired: '0x123...',
  },
  {
    id: 3,
    title: 'Decentralized Identity: The Future of Digital Trust',
    description: 'Exploring how DID systems are reshaping user authentication and privacy.',
    publishedAt: '2024-02-10',
    readTime: 6,
    stars: 98,
    views: 860,
    tags: ['identity', 'web3', 'privacy'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Polygon',
    tokenReward: 7,
  },
  {
    id: 4,
    title: 'Writing Smart Contracts in Solidity',
    description: 'Hands-on tutorial for writing and deploying smart contracts.',
    publishedAt: '2024-03-02',
    readTime: 10,
    stars: 210,
    views: 1800,
    tags: ['solidity', 'smart-contracts', 'ethereum'],
    coverImage: null,
    tokenGated: true,
    blockchain: 'Ethereum',
    tokenReward: 15,
  },
  {
    id: 5,
    title: 'Tokenomics: Designing Incentives in Web3',
    description: 'Learn how to build sustainable token economies.',
    publishedAt: '2024-03-15',
    readTime: 7,
    stars: 134,
    views: 1100,
    tags: ['tokenomics', 'incentives', 'crypto'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Arbitrum',
    tokenReward: 5,
  },
  {
    id: 6,
    title: 'NFTs for Writers: Ownership in the Digital Age',
    description: 'How NFTs empower authors with new monetization models.',
    publishedAt: '2024-03-28',
    readTime: 5,
    stars: 176,
    views: 1350,
    tags: ['nft', 'web3', 'writing'],
    coverImage: null,
    tokenGated: true,
    blockchain: 'Polygon',
    tokenReward: 8,
  },
  {
    id: 7,
    title: 'Building Decentralized Publishing Platforms',
    description: 'Architectural overview of peer-to-peer content systems.',
    publishedAt: '2024-04-01',
    readTime: 9,
    stars: 115,
    views: 990,
    tags: ['decentralized', 'publishing', 'content'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Ethereum',
    tokenReward: 6,
  },
  {
    id: 8,
    title: 'Building Decentralized Publishing Platforms',
    description: 'Architectural overview of peer-to-peer content systems.',
    publishedAt: '2024-04-01',
    readTime: 9,
    stars: 115,
    views: 990,
    tags: ['decentralized', 'publishing', 'content'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Ethereum',
    tokenReward: 6,
  },
  {
    id: 9,
    title: 'Building Decentralized Publishing Platforms',
    description: 'Architectural overview of peer-to-peer content systems.',
    publishedAt: '2024-04-01',
    readTime: 9,
    stars: 115,
    views: 990,
    tags: ['decentralized', 'publishing', 'content'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Ethereum',
    tokenReward: 6,
  },
  {
    id: 10,
    title: 'Building Decentralized Publishing Platforms',
    description: 'Architectural overview of peer-to-peer content systems.',
    publishedAt: '2024-04-01',
    readTime: 9,
    stars: 115,
    views: 990,
    tags: ['decentralized', 'publishing', 'content'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Ethereum',
    tokenReward: 6,
  },
  {
    id: 11,
    title: 'Building Decentralized Publishing Platforms',
    description: 'Architectural overview of peer-to-peer content systems.',
    publishedAt: '2024-04-01',
    readTime: 9,
    stars: 115,
    views: 990,
    tags: ['decentralized', 'publishing', 'content'],
    coverImage: null,
    tokenGated: false,
    blockchain: 'Ethereum',
    tokenReward: 6,
  },
];
