name: Next.js CI

on:
  schedule:
    # Runs every Sunday at 00:00 UTC
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Setup pnpm (this installs pnpm correctly on the runner)
      - name: Setup pnpm
        run: npm install -g pnpm

      # 4. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 5. Build Next.js
      - name: Build Next.js
        run: pnpm run build
